project_id = "wotwxzolgnsmzjpposua"

[functions.auth-signup-with-invite]
verify_jwt = false

[functions.bootstrap-admin-by-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false